site_name: milou
site_description: "milou: Methylation Integrated Layer for Omics Unification"
site_author: Jyotirmoy Das
repo_url: https://github.com/JD2112/milou
site_url: https://JD2112.github.io/milou/
edit_uri: ""

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    primary: blue grey
    accent: blue
  font:
    text: Inter
    code: Fira Code
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.expand
    - navigation.sections
    - navigation.top
    - content.code.annotate
    - content.tabs.link
    - navigation.tabs
    - search.suggest
    - search.highlight
    #- toc.follow
    - content.action.edit
    - content.code.copy
    - versioning
    - icons

plugins:
  - search
  - mike

nav:
  - Introduction: index.md
  - User Manual: usage.md  
  - Results: output.md
  - References: references.md

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.details  
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.extra
  - pymdownx.blocks.html
  - pymdownx.arithmatex:
      generic: true
  - codehilite
  - toc:
      permalink: true     
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  version:
    provider: mike
  current_year: !!python/object/apply:str ["2026"]

extra_css:
  - styles/extra.css
  - https://fonts.googleapis.com/css2?family=Fira+Code&family=Inter:wght@400;600&display=swap

extra_javascript:
  - js/mathjax.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
  - js/github-stats.js


