name: methylflow-unified
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - openpyxl
  - urllib3=2.6.3
  - requests=2.32.4
  - setuptools=82.0.1
  - wheel=0.46.2
  - brotli=1.2.0
  - cryptography=46.0.5
  - pyjwt>=2.12.0
